### ISSUE TITLE
SimulationsAPI - Type mismatch with API Schema

### ISSUE THREAD

**Issue by cdriesler** [pollination/node-sdk#2]
Calling `SimulationsApi.createSimulation()` in the current version (0.5.1) sends a post request with the following body format:

`{ "workflowSlug": "owner/project" }`

The [API specifies](https://api.pollination.cloud/#operation/create_simulation) `workflow_slug`, though, causing the request to fail. Can we push a fix to the SDK package?

This appears to be because of the types that ship with the SDK, which specify:

`SimulationsAPI.createSimulation(owner: string, name: string, submitSimulationDto: { workflowSlug: string })`

If I ignore the typings and just type `workflow_slug` the request goes through without any problems.

Ideally the types will match the data format, but for now I can use the `any` nuke and tell the linter to relax. Originally raised because it looked like a critical issue before the workaround was found.

**Comment by AntoineDao** [comment]
Yo! Had this been addressed by refreshing the SDK or is it still a problem? I noticed a similar issue with `workflowStatus` expecting `started_at` but receiving a parsed date as `startedAt`...

**Comment by cdriesler** [comment]
I haven't checked every type, but in general the API will return and expect snake case, and the types will only sometimes be generated in camel case. Haven't figured out why just yet, and it doesn't happen very often at all.

**Comment by cdriesler** [comment]
❤️
